### ISSUE TITLE
slow boot times

### ISSUE THREAD

**Issue by NeonLightning** [cy33hc/vita-launcher#1]
i've noticed when you open it there is a black screen for a while then reading the apps. so it takes some time to get into it. (btw i like it enough i'm using it with autoboot)

**Comment by cy33hc** [comment]
@NeonLightning What version are you on?

**Comment by NeonLightning** [comment]
i'm not sure i seem to recall i got it from homebrew database about 4 days ago i think

**Comment by cy33hc** [comment]
Try get the lastest version and see if you still have same problem. I made some startup improvements in v1.5 and in v1.6.1, I had improvement startup by 0.3 sec at least.

**Comment by NeonLightning** [comment]
seems to be better now. sorry i took so long i was hooked on a game lol
