### ISSUE TITLE
[Feature Request] Genesis Category Tile

### ISSUE THREAD

**Issue by Caspearious** [cy33hc/vita-launcher#18]
I have attached two tiles (black background and transparent background) for Genesis that I found, out on the Internets if you would like to add them in the icons folder.  Perfect replacement to the M-Drive tile if one chooses. 

Something to consider if possible in this code base, is to make all the category icons transparent and then allow for the background color to be changed for each category... defaulting to black (#000000).  Maybe include border radius, if that is also possible.

![segagenesis](https://user-images.githubusercontent.com/78292075/113492130-911b5600-94a3-11eb-8e54-b28e6d386458.png)

![segagenesis_t](https://user-images.githubusercontent.com/78292075/113492232-ff601880-94a3-11eb-8034-f22e8f84a11f.png)

**Comment by cy33hc** [comment]
@Caspearious Category icons are configurable. You can change the icon under the field "Category Icon" in the Settings Dialog. Make sure the icon size is 160x160 and png.

**Comment by cy33hc** [comment]
@Caspearious I will close this request since icons are configurable and user can choose icons according to their liking.
