### ISSUE TITLE
PS1 scan stalls mid-course

### ISSUE THREAD

**Issue by mightysashiman** [cy33hc/vita-launcher#19]
PS1 scan (be it the initial on-launch one or forcing rescan as an in-app action) will stall on some PS1 games (it did on Twisted metal 3, had to remove it for the scan to go past it, and is now stalling also at Croc - Legend of the Gobbos, and Croc 2, and Final Fantasy VII Retranslation).

Affected PS1 games run in adrenaline without any issues.

Let me know if I can help in anyway

**Comment by cy33hc** [comment]
@mightysashiman Fixed in release 9783c09e52a4e68d85a50cb3c3af4b9cb52e6602
