### ISSUE TITLE
PSPemu multiple paths

### ISSUE THREAD

**Issue by pet443** [cy33hc/vita-launcher#21]
Is there a way to add multiple PSPemu paths?

Example: UX0 & UMA0

**Comment by cy33hc** [comment]
@pet443 Sorry. At the moment you can only do either ux0 or uma0 not both at the same time.

**Comment by cy33hc** [comment]
@pet443 This is now implemented in release v3.4. ux0:pspemu will always be scanned for games. You can config an "Alternate Pspemu Path" in global settings now.
