### ISSUE TITLE
[Bug] Swap X/O buttons remembered but not used

### ISSUE THREAD

**Issue by cturczynskyj** [cy33hc/vita-launcher#22]
The settings menu seems to remember the "Swap X/O Buttons" setting (it shows properly in the settings menu) but when launching Vita Launcher, the launcher does not use this setting properly and you have to open the settings and scroll to "OK" once every time you start the launcher for the setting to take effect. 

What I mean by "doesn't use this setting properly" is that you can't select anything with either X or O in the launcher itself.

Using v3.0.

**Comment by cy33hc** [comment]
I reproduced the issue. Will fix it soon.

**Comment by cy33hc** [comment]
@cturczynskyj This is fixed in release 3.2 https://github.com/cy33hc/vita-launcher/releases/tag/v3.2
