### ISSUE TITLE
GPU crash when searching for stuff

### ISSUE THREAD

**Issue by f2pwn** [cy33hc/vita-launcher#30]
Happens 100% of the time when searching something with more than 32 positive results. Most of the time when exceeding 24. Sometimes when exceeding 16.

**Comment by cy33hc** [comment]
@f2pwn What games do you have in Vita Launcher and what were you search for. If possible, can you share your cache.db and config.ini

**Comment by cy33hc** [comment]
@f2pwn Not able to reproduce. There is a max of 300 games that will be searched. If you can provide the info, that would like troubleshoot.

**Comment by cy33hc** [comment]
@f2pwn @rafaelferreira01 Can you try update to latest release v3.7 and see if crash still happening.

**Comment by rafaelferreira01** [comment]
@cy33hc Updated to 3.7 and after about 50 searches i didn't faced any crashes.

**Comment by cy33hc** [comment]
@rafaelferreira01 @f2pwn I think the overclock helped with the crash, but I don't know why. I think there is a problem with imgui-vita2d library. It's the same problem with vita-ftp-client had problem with imgui-vita2d with random GPU crash, but after I switched to imgui-vita(opengl) the random crash is not happen.
