### ISSUE TITLE
Is it possible to hide categories which I'm no using? 

### ISSUE THREAD

**Issue by DaftOtter** [cy33hc/vita-launcher#31]
Hello, 

I was wondering if anyone knows how to hide categories that I'm not using.

For example, lets say I'm not using the Sega32x folder, and I have no games in there. Can I make it so this doesn't show up in the list of categories? Simply to tidy it up really...

Thanks

DaftOtter

**Comment by cy33hc** [comment]
@DaftOtter Go into a category and then under global settings, there show be an option called "Show all Categories". Uncheck that and it should hide all categories without games.

**Comment by XargonWan** [comment]
> @DaftOtter Go into a category and then under global settings, there should be an option called "Show all Categories". Uncheck that and it should hide all categories without games.

Can you please put this option even when outside the categories?
