### ISSUE TITLE
PSP/PSX custom game titles reset after library re-scan

### ISSUE THREAD

**Issue by C1fer** [cy33hc/vita-launcher#32]
If you set a custom name for a PSP or PSX game, it will only save that name until the app re-scans the categories.

Is there a way to store these custom names elsewhere? PSP ISO titles are all over the place, and it's not easy to rename the game title on the iso itself, since you'd have to edit the param.sfo.

**Comment by cy33hc** [comment]
@C1fer Is there a reason for re-scan? Is it to find new games?
