### ISSUE TITLE
How to disable update messages?

### ISSUE THREAD

**Issue by Tantris13** [cy33hc/vita-launcher#39]
How to turn off update messages?
I don't want to install an Adrenaline Bubble Manager - I don't need it right now. But every time you start the vita launcher, a message appears that without it it will not be possible to launch psp/etc games directly.
And the iTLS-ENSO install message - the launcher checks for the iTLS-ENSO installer bubble, not the installation. If the installer bubble is present, there is no message. If there is no installer bubble - even when installed, a message about the need to install iTLS-ENSO

**Comment by cy33hc** [comment]
@Tantris13 At the moment, there's not option to disable the update message. Short term just install both bubbles. I'll add option to disable update message.

**Comment by cy33hc** [comment]
@Tantris13 This is implemented and released in v3.7. The warning of missing iTLS-enso and ABB will only occur **ONCE** only.

**Comment by rafaelferreira01** [comment]
@cy33hc I dont have iTLS-enso or ABB and i see this popup every time i start vita-launcher.
![2022-05-18-111826](https://user-images.githubusercontent.com/78885729/169065572-9685343a-5b7e-49fb-90b9-8bd3b895a61a.jpg)
