### ISSUE TITLE
ScummVM Support

### ISSUE THREAD

**Issue by metaColin** [cy33hc/vita-launcher#4]
Loving the new launcher, but it'd be even better if it included my ScummVM titles.

Any chance of a ScummVM section being added?

**Comment by cy33hc** [comment]
@metaColin This requires the developer of ScummVM to make changes in his app to allow booting of the emulator with parameter for a pre-selected game.

**Comment by cy33hc** [comment]
@metaColin You'll need to convince ScummVM developers to support booting games from bubbles first. Somebody already requested. Maybe if there's more demand for it, then they might consider.

https://forums.scummvm.org/viewtopic.php?f=21&t=15205

**Comment by cy33hc** [comment]
@metaColin I have implemented some code changes in ScummVM to support bubbles and created a Pull Request to the ScummVM developer to include.
https://github.com/scummvm/scummvm/pull/2611

**Comment by cy33hc** [comment]
@metaColin @nowhereman87 My PR to support booting ScummVM has being accepted. Once ScummVM team releases this I can then support adding ScummVM to my launcher.

https://github.com/scummvm/scummvm/pull/2616

**Comment by nowhereman87** [comment]
Wow this is awesome, now those classic DOS and Amiga games could be started just as single ports, amazing addition, thanks a lot.

**Comment by metaColin** [comment]
cy33hc that is so amazing! You are a rockstar. I can't believe how quickly you managed to update not only your repo but also ScummVM's!!! Wow.

**Comment by cy33hc** [comment]
Release in 2.0
