### ISSUE TITLE
[Feature request] Option to close vita-launcher after launching a game.

### ISSUE THREAD

**Issue by rafaelferreira01** [cy33hc/vita-launcher#40]
Don't know if this is how it works but as vita-launcher uses AdrenalineLauncher and yoyo-launcher to launch the games to Adrenaline / Yoyo maybe it's possible to make then close vita-launcher before launching? Don't know how this would work with stuff that don't use a launcher (Retroarch, ports, etc) though.

**Comment by cy33hc** [comment]
@rafaelferreira01 vita-launcher is already being closed before Adernaline/YoYo/RetroArch launcher is stared. PSVITA can't have 2 apps running at the same time.

**Comment by rafaelferreira01** [comment]
@cy33hc Sorry, i wasn't very clear.
I'm talking about automatically "peel off" vita-launcher from LiveArea.

**Comment by cy33hc** [comment]
@rafaelferreira01 That's a vita thing. I can't do that.

**Comment by rafaelferreira01** [comment]
@cy33hc Oh, that's fine, is not even important, just something that occurred to me.
