### ISSUE TITLE
Boot Settings (Adrenaline) not being saved.

### ISSUE THREAD

**Issue by rafaelferreira01** [cy33hc/vita-launcher#41]
Don't know if this is designed but when we change any setting (Boot Settings tab) before launching a PSP or PSX game the settings are not being saved, so every time we open the game we have to make the changes.

**Comment by cy33hc** [comment]
@rafaelferreira01 Can you share a video? I tried with multiple games and they are saved.

**Comment by rafaelferreira01** [comment]
@cy33hc Here it is! If you need anuthing more just say.
https://user-images.githubusercontent.com/78885729/168897653-881ac2e1-9ab2-4daa-9363-af4e718fd251.mp4

**Comment by cy33hc** [comment]
@rafaelferreira01 Is that PSP game in EBOOT or ISO format?

**Comment by rafaelferreira01** [comment]
> @rafaelferreira01 Is that PSP game in EBOOT or ISO format?

CSO.

**Comment by rafaelferreira01** [comment]
@cy33hc Just tested a ISO and a EBOOT too, none of then are saving the settings.

**Comment by cy33hc** [comment]
@rafaelferreira01 can you include the cache.db and the game_settings.db file from the folder ux0:data/SMLA00001

**Comment by cy33hc** [comment]
@rafaelferreira01 Found the issue. I will create a fix for this.

**Comment by cy33hc** [comment]
@rafaelferreira01 Fixed in latest release

**Comment by rafaelferreira01** [comment]
@cy33hc Solved!
