### ISSUE TITLE
Adrenaline launcher can't launch a game after changing per game plugins

### ISSUE THREAD

**Issue by rafaelferreira01** [cy33hc/vita-launcher#42]
When we make some change on the per game plugins (enabling or disabling) and press Ok to launch the game the changes are saved (we can see that if we launch vita-launcher again) but AdrenalineLauncher won't launch the game. We have to open vita-launch again to be able to launch the game successfully. That applies to PSP and PSX games.

https://user-images.githubusercontent.com/78885729/168904555-724387dc-d84e-43e7-8160-95719f6c9ef2.mp4

**Comment by cy33hc** [comment]
@rafaelferreira01 This is probably related the issue #41 . Please check again after update and let me know if issue persist.

**Comment by cy33hc** [comment]
@rafaelferreira01 I saw in your previous videos, you didn't have this problem. Was there something you did later that caused this? Just trying to see what happened to trace down the issue.

**Comment by rafaelferreira01** [comment]
@cy33hc I never changed this settings before so i don't know if i had this problem. I only noticed it now while messing with plugins. Should i try a previous version?

**Comment by rafaelferreira01** [comment]
@cy33hc 
I've always had this problem with pergame plugins.

**Comment by cy33hc** [comment]
@rafaelferreira01 OK. Can you do this. When it won't boot, don't try to boot the game again. Instead goto VitaShell and grab this file for me "ux0:app/ADRLANCHR/data/boot.bin"

**Comment by cy33hc** [comment]
@rafaelferreira01 Fixed in latest release.
