### ISSUE TITLE
Plugin list cursor changing columns.

### ISSUE THREAD

**Issue by rafaelferreira01** [cy33hc/vita-launcher#43]
When we're browsing through the plugins and we press down, the cursor always go the delete column and when we press up it goes to the checkbox column. That applies to PSP Plugins and POPs Plugins, per game and global.

https://user-images.githubusercontent.com/78885729/168906292-feb7095d-32ff-42ae-99ab-44e6a3eec3ea.mp4

**Comment by cy33hc** [comment]
@rafaelferreira01 Improved the plugins navigation. Default selects the checkbox instead of "Delete" button
