### ISSUE TITLE
[Feature request] Close windows with a button

### ISSUE THREAD

**Issue by rafaelferreira01** [cy33hc/vita-launcher#44]
Right now we can hit Ok or Cancel to close windows (core selection, boot settings from PSP or PSX, Category settings, etc). It would be more fluid if we could, also, close these windows by pressing a button (circle?) and maybe without saving, like the present Cancel button.

**Comment by cy33hc** [comment]
@rafaelferreira01 Unfortunately, all buttons are already bound to per-defined actions. Sorry, I will have to reject this.
