### ISSUE TITLE
Update window every time i open vita-launcher.

### ISSUE THREAD

**Issue by rafaelferreira01** [cy33hc/vita-launcher#46]
I dont have iTLS-enso or ABB and i see this popup every time i start vita-launcher.
![169065572-9685343a-5b7e-49fb-90b9-8bd3b895a61a](https://user-images.githubusercontent.com/78885729/169578611-2f331eed-93d5-49c7-9499-521a258d9560.jpg)

**Comment by cy33hc** [comment]
@rafaelferreira01 fixed.
