### ISSUE TITLE
Duplicated PSP ROMs

### ISSUE THREAD

**Issue by gmartins-henrique** [cy33hc/vita-launcher#48]
Some ROMs are duplicated even after rescaning, and there is only one ISO of the game

**Comment by cy33hc** [comment]
@gmartins-henrique Do you have PSP Bubbles created with Adrenaline Bubble Manager? Those are usually what you see as duplicates. You can hide them.

**Comment by cy33hc** [comment]
@gmartins-henrique Thx. Yes, there is a bug. It's finding any file that with extension "PBP" and creating a entry. I'll fix it by constraint it to EBOOT.PBP only.

**Comment by cy33hc** [comment]
@gmartins-henrique Fixed on latest release.
