### ISSUE TITLE
[Feature Request]store psp settings

### ISSUE THREAD

**Issue by NeonLightning** [cy33hc/vita-launcher#5]
would you be able to store per-game settings for psp games?

**Comment by NeonLightning** [comment]
btw sorry to be so demanding. i just really see potential in this and as is i find it functional enough that I have it autoboot.

**Comment by cy33hc** [comment]
@NeonLightning Yeah. This can be done. Not a lot of work.

**Comment by NeonLightning** [comment]
yes that would be great.
what would be even better is if you could choose what plugins are enabled when you turn on plugins. i understand if that's not doable as i don't think abb is able to do that.

**Comment by cy33hc** [comment]
@NeonLightning PSP booting depends on abb, so yeah not possible at the moment.

**Comment by cy33hc** [comment]
Implemented in release 1.9.1
