### ISSUE TITLE
crashes while scanning psp homebrew.

### ISSUE THREAD

**Issue by NeonLightning** [cy33hc/vita-launcher#6]
is there logging anywhere in this? i'm encountering a crash as it scans in my psp homebrew. i'm not sure how to troubleshoot it other than repeatedly moving out each program and opening launcher to scan again.

**Comment by cy33hc** [comment]
@NeonLightning Latest version allows you to add 1 PSP ISO/EBBOT at a time. You can add 1 add at a time without rescan all psp game to see which game have problem.

**Comment by NeonLightning** [comment]
it was GeMP

**Comment by cy33hc** [comment]
@NeonLightning Let me give it a try and see what's problem with that EBOOT.

**Comment by cy33hc** [comment]
@NeonLightning It's missing the DISC_ID attribute in the param.sfo. I'll have to handle missing attributes.

**Comment by cy33hc** [comment]
@NeonLightning Fix pushed. Will be part of next release
