### ISSUE TITLE
 c1-2758-2 Error when opening Adrenaline Launcher

### ISSUE THREAD

**Issue by ImMrShrike** [cy33hc/vita-launcher#7]
Every time I try to open Adrenaline Launcher, i get  c1-2758-2 error

**Comment by cy33hc** [comment]
@ImMrShrike 
You need to install Adrenaline Bubble Booter plugin. You can get this plugin by installing "Adrenaline Bubble Manager" and launch it for first time to install it. After that you can remove "Adrenaline Bubble Manager". 

https://github.com/ONElua/AdrenalineBubbleManager/releases

**Comment by ImMrShrike** [comment]
I'm now getting "Could not load adrenaline kernel.skprx please reboot or use adrbubble booter installer", I tried to install other bubbles via "Adrenaline Bubble Manager" and they work fine.
I'm on PS TV with usbmc plugin, if it can help

**Comment by ImMrShrike** [comment]
also, launching a psp game via vita launcher (not the ones I created the bubble) gives c1-2650-3

**Comment by cy33hc** [comment]
@ImMrShrike What version of Adrenaline do you have, 6.61 or v7? Based on the version you need to install the proper Adrenaline Bubble Booter plugin.

**Comment by cy33hc** [comment]
@ImMrShrike You might want to reinstall adrenaline and then install ABM again. See issue reported here.
https://github.com/ONElua/AdrenalineBubbleManager/issues/28

**Comment by cy33hc** [comment]
@ImMrShrike Closing issue since this is more of an Adrenaline plugin setup mismatch issue.

**Comment by Majdoubi-Abdessamad** [comment]
bza3at
