### ISSUE TITLE
Adrenaline reboots when I launch psp compilation games 

### ISSUE THREAD

**Issue by Riccobene** [cy33hc/vita-launcher#8]
Hi,

When I launch a psp compilation game via vita launcher (I've seen it with isos like Capcom classics reloaded, metal slug anthology, crazy taxi fare wars), and then I select a game from the compilation to start,  adrenaline reboors and I have to launch the game again, from Adrenaline this time! Then, the game starts well!
It's something that happens to anyone else?

Thank you to the developer for this great homebrew!  (and sorry for my bad English)

**Comment by cy33hc** [comment]
@Riccobene Can you share a video of the problem.

**Comment by Riccobene** [comment]
Sure!

Game 1

https://youtu.be/Q_KJSUU1Uss

Game 2

https://youtu.be/TWo-5_w3IPQ

Game 3

https://youtu.be/SUeikW2RBco

**Comment by cy33hc** [comment]
@Riccobene For that issue, I believe some people mentions that you might need to change the driver to either march33 or np9660

**Comment by Riccobene** [comment]
@cy33hc yes, it does work! Thanks again!
