### ISSUE TITLE
The variable "icon_path" doesn't work if it's different from "rom_path"

### ISSUE THREAD

**Issue by afdc98** [cy33hc/vita-launcher#9]
My icons won't load if the "icon_path" set is different from the "rom_path" (I think those are their names) in the NES/SNES/GBA/GBC... categories. However, even if those variables are different, my icons load if they are placed in the folder in "rom_path", so it's like the "icon_path" variable doesn't work, and the app only takes into account the folder where the roms are placed.

I can post screenshots if needed, thank you.

**Comment by cy33hc** [comment]
Uncheck the option "new icon method" from "Global" settings. That forces icons to be located where the ROM is located.

**Comment by cy33hc** [comment]
@afdc98 Can you validate my responds. If I don't get feedback in couple of days. I'll close this issue.

**Comment by afdc98** [comment]
yes, it works with the new icon method disabled, thanks!
